language: php

cache:
  directories:
    - vendor

php:
  - 5.6

before_script:
  - composer selfupdate
  - composer install --dev --prefer-dist
  - composer require codeclimate/php-test-reporter

script:
  - ./vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_success:
 - ./vendor/bin/test-reporter --coverage-report build/logs/clover.xml