<?php
namespace DbConnection;

use DbConnection\Db as Db;

/**
 * Test class for Db.
 * Generated by PHPUnit on 2009-12-20 at 04:58:52.
 */
class DbTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var    Db
     * @access protected
     */
    protected $_object;

    const METADATA_PATH = __DIR__ . '/../config/queries.xml';

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     *
     * @access protected
     */
    protected function setUp()
    {
        $this->_object = new Db(self::METADATA_PATH);
    }

    public function testGetConnectionExists()
    {
        $this->assertTrue(method_exists($this->_object, 'getConnection'));
    }

    public function testMagicCallExists()
    {
        $this->assertTrue(method_exists($this->_object, '__call'));
    }

    public function testGetSqlExists()
    {
        $this->assertTrue(method_exists($this->_object, 'getSql'));
    }

    public function testSetSqlExists()
    {
        $this->assertTrue(method_exists($this->_object, 'setSql'));
    }
}
