<?php
namespace DbConnection;

require_once 'PHPUnit/Autoload.php';
require_once dirname(__FILE__) . '/../../src/Metadata.php';

/**
 * Test class for Metadata.
 * Generated by PHPUnit on 2012-01-06 at 04:53:44.
 */
class MetadataTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var Metadata
     */
    protected $_object;

    const METADATA_PATH = '../config/queries.xml';

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->_object = new Metadata(self::METADATA_PATH);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }

    public function testConstructExists()
    {
        $this->assertTrue(method_exists($this->_object, '__construct'));
    }

    public function testSetXmlReturnExceptionFileNotFound()
    {
        $this->setExpectedException('DbConnection\MetadataException');
        new Metadata();
    }

    public function testSetXmlExists()
    {
        $this->assertTrue(method_exists($this->_object, 'setXml'));
    }

    public function testSetXmlReturnObject()
    {
        $object = is_object($this->_object->setXml(self::METADATA_PATH));
        $this->assertTrue($object);
    }

    public function testSetGetXmlExists()
    {
        $this->assertTrue(method_exists($this->_object, 'getXml'));
    }

    public function testGetConnectionExists()
    {
        $this->assertTrue(method_exists($this->_object, 'getConnection'));
    }

    public function testGetConnectionReturnObject()
    {
        $this->assertTrue(is_object($this->_object->getConnection('default')));
    }

    public function testGetDefaultConnectionExists()
    {
        $this->assertTrue(method_exists($this->_object, 'getDefaultConnection'));
    }

    public function testGetDefaultConnectionReturnObject()
    {
        $this->assertTrue(is_object($this->_object->getDefaultConnection()));
    }

    public function testGetSqlExists()
    {
        $this->assertTrue(method_exists($this->_object, 'getSql'));
    }

    public function testGetSqlReturnArray()
    {
        $this->assertTrue(is_array($this->_object->getSql('dataAtual')));
    }
}
